[package]
name = "docktor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "6.0.0"
plist = "1.7"
serde = { version = "1.0", features = ["derive"] }
